# Generated by Django 3.0.4 on 2020-04-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[(0, 'UserRegistration'), (1, 'PasswordReset')], max_length=2)),
                ('is_sent', models.BooleanField(default=False)),
                ('validation_code', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
