# Generated by Django 3.0.4 on 2020-04-13 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='EmailValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('validation_code', models.IntegerField()),
                ('type', models.CharField(choices=[(0, 'UserRegistration'), (1, 'PasswordReset')], max_length=2)),
                ('code_used', models.BooleanField(default=False)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email')),
            ],
        ),
    ]
